spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
            - Path=/api/authors/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          okta:
            issuer-uri: ${ISSUER_URI}

okta:
  oauth2:
    issuer: ${ISSUER_URI}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    audience: ${ISSUER_URI}api/v2/

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

logging:
  level:
    org:
      springframework:
        security: DEBUG
